services:
  event-registration-services:
    build: .
    container_name: event-registration-services
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on: 
      - mongodb
    networks:
      - event-registration-network
    command: npm start
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: event_registration
    volumes: 
      - data_event_registration:/data/db
    networks:
      - event-registration-network
volumes:
  data_event_registration:
    driver: local
networks:
  event-registration-network:
    driver: bridge
 
 
    